---
framework:
  - ansible
  - argo_workflows
  - arm
  - bicep
  - cloudformation
  - dockerfile
  - helm
  - kubernetes
  - kustomize
  - openapi
  - serverless
  - terraform
  - terraform_json
  - terraform_plan
skip-check: []
compact: true
download-external-modules: false
evaluate-variables: false
skip-download: true
skip-results-upload: true
